--- 
clone: 
  depth: 1
kind: pipeline
name : OldCam
version: XTREME-OLD
steps:
 - name: Xtreme
   image: ubuntu:jammy-20211029
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - cp -af sources.list /etc/apt/
     - cp -af 99own /etc/apt/apt.conf.d/
     - apt update && apt upgrade -y
     - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
     - apt install -f -y git bison flex libxml2 libssl-dev bc zip ccache p7zip default-jre python3 python3-pip wget curl
     - bash build --old

---
clone:
  depth: 1
kind: pipeline
name : NewCam
version: XTREME-NEW
steps:
 - name: Xtreme
   image: ubuntu:jammy-20211029
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - cp -af sources.list /etc/apt/
     - cp -af 99own /etc/apt/apt.conf.d/
     - apt update && apt upgrade -y
     - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
     - apt install -f -y git bison flex libxml2 libssl-dev bc zip ccache p7zip default-jre python3 python3-pip wget curl
     - bash build --new

---
kind: pipeline
name : Qti-Old
version: XTREME-QTI-OLD
steps:
 - name: Xtreme
   image: ubuntu:jammy-20211029
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - cp -af sources.list /etc/apt/
     - cp -af 99own /etc/apt/apt.conf.d/
     - apt update && apt upgrade -y
     - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
     - apt install -f -y git bison flex libxml2 libssl-dev bc zip ccache p7zip default-jre python3 python3-pip wget curl
     - git fetch https://github.com/ImSpiDy/Nexus-Xtreme-Kernel Qti
     - git cherry-pick f6bcac58941a4ecb1646819464298f8aa4d91571^..4c27e5c6303ebc2bda849dd97223f734762c20f6
     - bash build --qti
